server:
  port: 18081
spring:
  rabbitmq:
    virtual-host: /java0509
    host: 49.4.69.64
    username: java0509
    password: java0509
    port: 5672
    publisher-confirms: true
    publisher-returns: true
    listener:
      simple:
        acknowledge-mode: manual
